name: Submit Vote

on:
  push:
    paths:
      - 'vote_request_user.json'

jobs:
  process_vote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Promote vote_request_user → vote_request
        run: cp vote_request_user.json vote_request.json

      - name: Update votes.json
        run: |
          if [ ! -f votes.json ]; then echo '{}' > votes.json; fi
          city=$(jq -r '.city' vote_request.json)
          jq "if .[\"$city\"] then .[\"$city\"] += 1 else .[\"$city\"] = 1 end" votes.json > tmp.json && mv tmp.json votes.json

      - name: Append to Voting_Log.txt
        run: |
          echo "$(date -u +"%Y-%m-%dT%H:%M:%SZ") :: $(jq -r '.user' vote_request.json) voted for $(jq -r '.city' vote_request.json)" >> Voting_Log.txt

      - name: Clean up request
        run: rm vote_request_user.json

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Registered vote"