name: Log Voting Events

on:
  workflow_dispatch:
  push:
    paths:
      - 'votes.json'
      - 'weekly_cities.json'
      - 'City_Database.json'

jobs:
  update-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run logging script
        run: python .github/scripts/update_log.py

      - name: Commit and push log
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add voting_log.md
          git commit -m "📝 Log updated"
          git push